# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - run: npm install
      - run: npm run build
      # save dist folder to cache
      - save_cache:
          key: dist-cache-{{ checksum "package-lock.json" }}
          paths:
            - dist
  store_to_artifact:
    docker:
      - image: cimg/node:16.3.0
    steps:
      # restore node_modules from cache
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - store_artifacts:
          path: dist

# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  # This is the name of the workflow, feel free to change it to better match your workflow.
  sample_workflow:
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
      - store_to_artifact
